export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

export const LISTADO_PRODUCTO_INICIO = 'LISTADO_PRODUCTO_INICIO';
export const LISTADO_PRODUCTO_EXITO = 'LISTADO_PRODUCTO_EXITO';
export const LISTADO_PRODUCTO_ERROR = 'LISTADO_PRODUCTO_ERROR';

export const OBTENER_PRODUCTO_ELIMINAR = 'OBTENER_PRODUCTO_ELIMINAR';
export const PRODUCTO_ELIMINADO_EXITO = 'PRODUCTO_ELIMINADO_EXITO';
export const PRODUCTO_ELIMINADO_ERROR = 'PRODUCTO_ELIMINADO_ERROR';

export const OBTENER_PRODUCTO_EDITAR = 'OBTENER_PRODUCTO_EDITAR'
export const INICIAR_EDICION_PRODUCTO = 'INICIAR_EDICION_PRODUCTO'
export const PRODUCTO_EDITAR_EXITO = 'PRODUCTO_EDITAR_EXITO'
export const PRODUCTO_EDITAR_ERROR = 'PRODUCTO_EDITAR_ERROR'